apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
  namespace: fargate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        agent.datadoghq.com/sidecar: "fargate"
      name: redis
    spec:
      serviceAccountName: datadog-agent
      containers:
      - name: redis
        image: redis:7
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
          requests:
            memory: "128Mi"
            cpu: "100m"
